# Generated by Django 4.0.2 on 2022-02-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.ManyToManyField(related_name='category', through='gamerraterapi.GameCategory', to='gamerraterapi.Category'),
        ),
    ]
